### ISSUE TITLE
Every day at x not working

### ISSUE THREAD

**Issue by limoli** [sbrki/clockwork#12]
Today is **17th April 2018**.

I execute the following command:
`sched.Schedule().Every().Day().At("18:00").Do(task)`

The result is:
`Scheduled for  2019-04-18 18:00:00 +0200 CEST`

Why tomorrow and not today?
I don't think that this library is well tested. 
I read another issue about weekday.

**Comment by sbrki** [comment]
Here, fixed it. Please check that it works fine so I can close the issue.
The problem was that the job was automatically scheduled for the next day, even if it was possible to schedule it for today.

>I don't think that this library is well tested.

@virup was very kind and wrote tests that cover the most common use cases. It actually caught a mistake as I was fixing this issue. I'll write more comprehensive tests soon.

On a more personal note, I see you are opening issues and I hope you are aware this is a library I hacked in a day, I needed a simple & dirty library like this one for a toy project I was working on. I'm planning to refactor this project up a notch in the following weeks since some folks started using it (damn you folks!). If you are using this library as-is for a more serious project, I discourage you from doing so (at least until I fix all the issues), as there are more mature and serious alternatives out there.

Also thanks for pointing the issue out! :)
